export const gamesCatalog = [
  {
    slug: 'plane-forest-run',
    titleKey: 'games.planeForestRun.title',
    descriptionKey: 'games.planeForestRun.description',
    ageKey: 'ages.3plus',
    ageGroup: '3plus',
    image: '/games/plane-forest-run-preview.svg',
    skills: ['skills.flight', 'skills.focus'],
    path: '/games/plane-forest-run',
  },
  {
    slug: 'corgi-math-run',
    titleKey: 'games.corgiMathRun.title',
    descriptionKey: 'games.corgiMathRun.description',
    ageKey: 'ages.3plus',
    ageGroup: '3plus',
    image: '/games/corgi-math-run-preview.svg',
    skills: ['skills.math', 'skills.focus'],
    path: '/games/corgi-math-run',
  },
  {
    slug: 'train-track-builder',
    titleKey: 'games.trainTrackBuilder.title',
    descriptionKey: 'games.trainTrackBuilder.description',
    ageKey: 'ages.3plus',
    ageGroup: '3plus',
    image: '/games/train-track-builder-preview.svg',
    skills: ['skills.logic', 'skills.spatial'],
    path: '/games/train-track-builder',
  },
  {
    slug: 'train-station-builder',
    titleKey: 'games.trainStationBuilder.title',
    descriptionKey: 'games.trainStationBuilder.description',
    ageKey: 'ages.3plus',
    ageGroup: '3plus',
    image: '/games/train-station-builder-preview.svg',
    skills: ['skills.logic', 'skills.spatial', 'skills.planning'],
    path: '/games/train-station-builder',
  },
  {
    slug: 'typing-balloons',
    titleKey: 'games.typingBalloons.title',
    descriptionKey: 'games.typingBalloons.description',
    ageKey: 'ages.3plus',
    ageGroup: '3plus',
    image: '/games/typing-balloons-preview.svg',
    skills: ['skills.typing', 'skills.letterOrder', 'skills.focus'],
    path: '/games/typing-balloons',
  },
  {
    slug: 'color-shape-sorter',
    titleKey: 'games.colorShapeSorter.title',
    descriptionKey: 'games.colorShapeSorter.description',
    ageKey: 'ages.3plus',
    ageGroup: '3plus',
    image: '/games/color-shape-sorter-preview.svg',
    skills: ['skills.logic', 'skills.colors', 'skills.shapes'],
    path: '/games/color-shape-sorter',
  },
  {
    slug: 'memory-cards',
    titleKey: 'games.memoryCards.title',
    descriptionKey: 'games.memoryCards.description',
    ageKey: 'ages.4plus',
    ageGroup: '4plus',
    image: '/games/memory-cards-preview.svg',
    skills: ['skills.memory', 'skills.focus'],
    path: '/games/memory-cards',
  },
  {
    slug: 'word-builder',
    titleKey: 'games.wordBuilder.title',
    descriptionKey: 'games.wordBuilder.description',
    ageKey: 'ages.5plus',
    ageGroup: '5plus',
    image: '/games/word-builder-preview.svg',
    skills: ['skills.typing', 'skills.letterOrder', 'skills.logic'],
    path: '/games/word-builder',
  },
];
