export const gamesCatalog = [
  {
    slug: 'plane-forest-run',
    titleKey: 'games.planeForestRun.title',
    descriptionKey: 'games.planeForestRun.description',
    ageKey: 'ages.3plus',
    ageGroup: '3plus',
    image: '/games/plane-forest-run-preview.svg',
    skills: ['skills.flight', 'skills.focus'],
    path: '/games/plane-forest-run',
  },
  {
    slug: 'corgi-math-run',
    titleKey: 'games.corgiMathRun.title',
    descriptionKey: 'games.corgiMathRun.description',
    ageKey: 'ages.3plus',
    ageGroup: '3plus',
    image: '/games/corgi-math-run-preview.svg',
    skills: ['skills.math', 'skills.focus'],
    path: '/games/corgi-math-run',
  },
  {
    slug: 'typing-balloons',
    titleKey: 'games.typingBalloons.title',
    descriptionKey: 'games.typingBalloons.description',
    ageKey: 'ages.3plus',
    ageGroup: '3plus',
    image: '/games/typing-balloons-preview.svg',
    skills: ['skills.typing', 'skills.letterOrder', 'skills.focus'],
    path: '/games/typing-balloons',
  },
];
